config/routes.rb
Rails.application.routes.draw do
  resources :inspos
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inspo.rb
class Inspo < ApplicationRecord
  belongs_to :user
  has_attached_file :image, :styles => { large: "600x600>", medium: "300x300>", thumb:"150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :inspos
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/inspos_controller.rb
class InsposController < ApplicationController
  before_action :set_inspo, only: [:show, :edit, :update, :destroy]

  # GET /inspos
  # GET /inspos.json
  def index
    @inspos = Inspo.all
  end

  # GET /inspos/1
  # GET /inspos/1.json
  def show
  end

  # GET /inspos/new
  def new
    @inspo = Inspo.new
  end

  # GET /inspos/1/edit
  def edit
  end

  # POST /inspos
  # POST /inspos.json
  def create
    @inspo = Inspo.new(inspo_params)

    respond_to do |format|
      if @inspo.save
        format.html { redirect_to @inspo, notice: 'Inspo was successfully created.' }
        format.json { render :show, status: :created, location: @inspo }
      else
        format.html { render :new }
        format.json { render json: @inspo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspos/1
  # PATCH/PUT /inspos/1.json
  def update
    respond_to do |format|
      if @inspo.update(inspo_params)
        format.html { redirect_to @inspo, notice: 'Inspo was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspo }
      else
        format.html { render :edit }
        format.json { render json: @inspo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspos/1
  # DELETE /inspos/1.json
  def destroy
    @inspo.destroy
    respond_to do |format|
      format.html { redirect_to inspos_url, notice: 'Inspo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inspo
      @inspo = Inspo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspo_params
      params.require(:inspo).permit(:caption, :image)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def index
    
  end

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:inspos, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # redirect_to(:users, notice: 'User was successfully created')
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inspos_helper.rb
module InsposHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inspos/_form.html.erb
<%= form_for inspo, html: { multipart: true } do |f| %>
  <% if inspo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inspo.errors.count, "error") %> prohibited this inspo from being saved:</h2>

      <ul>
      <% inspo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <!-- <span class="btn btn-info btn-file"> -->
    <%= f.file_field :image %>
  <!-- </span> -->
  </div>

  <div class="field">
    <%= f.label :caption %>
    <%= f.text_area :caption %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/inspos/edit.html.erb
<h1 class="inspo_title">Editing Inspo</h1>

<%= render 'form', inspo: @inspo %>

<%= link_to 'Show', @inspo %> |
<%= link_to 'Back', inspos_path %>

app/views/inspos/index.html.erb
<p id="notice"><%= notice %></p>

<!-- INDEX PAGE HEADING -->
<p id="top-title">Share your</p>
<div class="title_box">
  <h1 id="index-inspo">Inspo</h1>
</div>


<!-- IMAGE GALLERY -->
<table>
  <thead>
    <tr>
      <th id="vibe-line">VIBE-LINE</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @inspos.each do |inspo| %>
      <tr>
        <td><%= inspo.caption %></td>
        <td><%= image_tag inspo.image.url(:medium) %></td>
        <td><%= link_to 'Show', inspo %></td>
        <td><%= link_to 'Edit', edit_inspo_path(inspo) %></td>
        <td><%= link_to 'Destroy', inspo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inspo', new_inspo_path, class:"btn btn-primary"%>

app/views/inspos/new.html.erb
<!-- ADDING A NEW INSPO -->
<h1 id="new-inspo">New Inspo</h1>

<div class="new-inspo-form">
  <%= render 'form', inspo: @inspo %>
</div>

<%= link_to 'Back', inspos_path, class:"btn btn-default" %>

app/views/inspos/show.html.erb
<p id="notice"><%= notice %></p>

<div id="move-show-form">
 <%= image_tag @inspo.image.url(:medium) %>

<p>
  <strong>Caption:</strong>
  <%= @inspo.caption %>
</p>
</div>

<%= link_to 'Edit', edit_inspo_path(@inspo), class:'btn btn-default' %> |
<%= link_to 'Back', inspos_path, class:'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inspo</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>

<body>

  <div id="nav">
    <% if current_user %>
    <%= link_to 'New Inspo', new_inspo_path, class:"btn btn-primary"%>
    <%= link_to "Edit Profile", edit_user_path(current_user.id), class:"btn btn-default" %>
    <%= link_to "Logout", :logout, method: :post, class:"btn btn-warning" %>
    <% else %>
    <%= link_to "Register", new_user_path, class:"btn btn-success" %>
    <%= link_to "Login", :login, class:"btn btn-info" %>
    <% end %>
  </div>
  <div>
    <!-- <p id="notice"><%= flash[:notice] %></p> -->
    <p id="alert"><%= flash[:alert] %></p>
  </div>

  <%= yield %>
</body>
</html>

app/views/user_sessions/_form.html.erb
<div class="login_form_body">

<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, "", class:"login_form" %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password, "", class:"login_form" %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" , class:"btn btn-info" %>
  </div>
<% end %>
</div>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1 id="login_index_title">Login</h1>

<div class="login-form">
  <%= render 'form' %>
</div>

<div class="back_button_pos">
  <%= link_to 'Back', users_path, class:"btn btn-default"%>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- DIV FOR NEW USER FORM  -->

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email, class:"new-user-form" %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, class:"new-user-form" %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class:"new-user-form" %>
    </div>

    <div class="actions">
      <%= f.submit class:"btn btn-success" %>
    </div>


  <% end %>

app/views/users/edit.html.erb
<!--- EDIT USER PROFILE  -------------->

<h1 id="edit-profile">Edit Profile</h1>

<div id="edit-form">
  <%= render 'form', user: @user %>
</div>

<%= link_to 'Show', @user, class:'btn btn-info'%> |
<%= link_to 'Back', users_path, class:'btn btn-default' %>

app/views/users/index.html.erb
<!-- INSPO HOMEPAGE (LOGIN/REGISTER) -->
<body id="root_pic">
  <p id="notice"><%= notice %></p>
  <div>
    <h1 class="inspo_title">Inspo</h1>
  </div>
</body>











<!-- <table>
  <thead>
    <tr>
      <th>Email</th> -->
      <!-- <th>Crypted password</th>
      <th>Salt</th> -->
      <!-- <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td> -->
        <!-- <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td> -->
        <!-- <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1 id="welcome-inspo">Welcome to INSPO</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class:'btn btn-default' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user), class:'btn btn-primary' %> |
<%= link_to 'Back', users_path, class:'btn btn-default'%>